version: "{{ config.docker_compose.version }}"

services:
{% for service, data in services %}
    {{ service }}:
        volumes:
            - "{{ recipe_path }}/bin/user_fix_entrypoint.sh:/user_fix_entrypoint.sh"
        entrypoint: "/user_fix_entrypoint.sh"
        environment:
            UID:                      {{ data.uid }}
            GID:                      {{ data.gid }}
            CONTAINER_USER:           {{ data.user }}
            CONTAINER_GROUP:          {{ data.group }}
            # We have to encode it with base64. We try to avoid yaml or other parsing problems with complex entrypoint commands.
            CONTAINER_ENTRYPOINT_B64: '{{ data.entrypoint|base64 }}'

{% endfor %}
