FROM fchris82/wf

# Useful paths in ENV
#   - SYMFONY_PATH
#   - SYMFONY_CONSOLE

# Add VCS and the new extension (OAuth: https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens )
#ARG WF_SYMFONY_ENV=prod
#RUN cd ${SYMFONY_PATH} && \
#    composer clearcache && \
#    composer config repositories.repo-name vcs https://github.com/custom/wf-extension.git && \
#    composer config -g github-oauth.github.com <oauthtoken> && \
#    wf-composer-require "custom/wf-extension"
